### ISSUE TITLE
string indices must be inetegers

### ISSUE THREAD

**Issue by ShiraziElham** [n3r/qase-testrail-migration#2]
https://github.com/n3r/qase-testrail-migration/blob/dca41078d7779026706a9493b28e85222440fbc1/importer.py#L73

Hello,
I am trying this script and here is what error I am getting:

[Importer] Loading projects from TestRail...
> /usr/lib/python3/dist-packages/requests/sessions.py(625)send()
-> kwargs.setdefault('stream', self.stream)
(Pdb) cont
[Importer] Found projects: 5
Traceback (most recent call last):
  File "start.py", line 33, in <module>
    importer.start()
  File "/home/elham/source/qase/qase-testrail-migration/importer.py", line 73, in start
    if (project['is_completed'] == False and self._check_import(project['name'])):
TypeError: string indices must be integers

I provided the output I am recieving above. Here is my two different inputs that led me to that error:
---------------------- 1st input ----------------------
"projects": [
    "AB Global",
    {
      "name": "AB Global"
    }
  ],
---------------------- 2nd input ----------------------
"projects": ["AB Global"],

Please advice. Thanks.

**Comment by ShiraziElham** [comment]
solution seems to be : 
on importer.cy , on line 72 and 110 , instead of 
`for project in self.projects:`
we needed `for project in self.projects['projects']:`.

Now I am getting anothet error. Here is my output for both inputs showing after it:

Traceback (most recent call last):
  File "start.py", line 33, in <module>
    importer.start()
  File "/home/elham/source/qase/qase-testrail-migration/importer.py", line 104, in start
    self._create_suites(code, project['id'], None)
  File "/home/elham/source/qase/qase-testrail-migration/importer.py", line 175, in _create_suites
    sections = self._get_sections(testrail_project_id, testrail_suite_id)
  File "/home/elham/source/qase/qase-testrail-migration/importer.py", line 210, in _get_sections
    sections = self.testrail.send_get('get_sections/' + str(project_id) + f'&suite_id={suite_id}&limit={limit}&offset={offset}')
  File "/home/elham/source/qase/qase-testrail-migration/testrail.py", line 39, in send_get
    return self.__send_request('GET', uri, filepath)
  File "/home/elham/source/qase/qase-testrail-migration/testrail.py", line 85, in __send_request
    raise APIError('TestRail API returned HTTP %s (%s)' % (response.status_code, error))
testrail.APIError: TestRail API returned HTTP 400 ({'error': 'Field :suite_id is not a valid ID.'})

my 1st input was:
"projects": [
    "AB Global",
    {
      "name": "AB Global",
      "suits": [5545]
}
]

my 2nd input was:
"projects": [ "AB Global"]

as you see even when I do not identify any suites ( to get all of them ) still getting the same error. Please assist.
